# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: running.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrunning.proto\x12\x07running\"L\n\x14WeeklyMileageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tstartDate\x18\x02 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x03 \x01(\t\".\n\rWeeklyMileage\x12\x0c\n\x04week\x18\x01 \x01(\t\x12\x0f\n\x07mileage\x18\x02 \x01(\x01\"A\n\x15WeeklyMileageResponse\x12(\n\x08mileages\x18\x01 \x03(\x0b\x32\x16.running.WeeklyMileage2b\n\x07Running\x12W\n\x14GetUserWeeklyMileage\x12\x1d.running.WeeklyMileageRequest\x1a\x1e.running.WeeklyMileageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'running_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WEEKLYMILEAGEREQUEST']._serialized_start=26
  _globals['_WEEKLYMILEAGEREQUEST']._serialized_end=102
  _globals['_WEEKLYMILEAGE']._serialized_start=104
  _globals['_WEEKLYMILEAGE']._serialized_end=150
  _globals['_WEEKLYMILEAGERESPONSE']._serialized_start=152
  _globals['_WEEKLYMILEAGERESPONSE']._serialized_end=217
  _globals['_RUNNING']._serialized_start=219
  _globals['_RUNNING']._serialized_end=317
# @@protoc_insertion_point(module_scope)
