# GitHub Action for formatting code.
# Author: Andrew Jarombek
# Date: 1/29/2023

name: Databricks Terraform Formatting and Planning

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  format_and_plan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Job running on a ${{ runner.os }} server"

      - name: Check Out Repository Code
        uses: actions/checkout@v3

      - run: echo "Checked out branch '${{ github.ref }}' of the ${{ github.repository }} repository"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Format
        working-directory: ./databricks/infra
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ./databricks/infra
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        working-directory: ./databricks/infra
        run: terraform validate -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        working-directory: ./databricks/infra
        run: terraform plan -no-color -input=false
        env:
          TF_VAR_databricks_account_username: ${{ secrets.DATABRICKS_ACCOUNT_USERNAME }}
          TF_VAR_databricks_account_password: ${{ secrets.DATABRICKS_ACCOUNT_PASSWORD }}
          TF_VAR_databricks_account_id: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
