# GitHub Action for running Go tests
# Author: Andrew Jarombek
# Date: 9/21/2022

name: Go Tests

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  go_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: ajarombek/go-alpine-linux-programming:latest
    steps:
      - run: echo "Job running on a ${{ runner.os }} server"

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "Checked out branch '${{ github.ref }}' of the ${{ github.repository }} repository"

      - name: Files installed from repository
        working-directory: ./go
        run: ls -ltra

      - name: Run Go tests using Please Build
        working-directory: ./go
        run: plz test //... -i test -vvv
