name: Python Format Commit

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:

jobs:
  format_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Format Python Code
        run: |
          python -m pip install --upgrade pip
          pip install black
          black python

      - name: Commit and Push Formatting Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Andrew Jarombek
          author_email: andrew@jarombek.com
          message: 'Format Python Code with Black'