name: Python Format Commit

on:
  push:
    branches:
      - 'feature/*'
    paths:
      - 'python/**.py'

  workflow_dispatch:

jobs:
  format_commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Format Python Code
        run: |
          python -m pip install --upgrade pip
          pip install black
          black python

      # For this to work, set read and write permissions for actions in the repository settings.
      - name: Commit and Push Formatting Changes
        run: |
          git config --global --add safe.directory $(realpath .)
          git config user.email "andrew@jarombek.com"
          git config user.name "Andrew Jarombek"
          git add .
          
          if [[ -n $(git status -s) ]]; then
            git commit -m "Format Python Code with Black"
            git push https://AJarombek:${{ secrets.GIT_PAT }}@github.com/AJarombek/andy-jarombek-research.git
            echo "Changes committed and pushed to the remote repository."
          else
            echo "No local changes to commit and push."
          fi
        shell: bash