name: React GraphQL JS Format Commit

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  format_commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: node:18.16.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Yarn
        working-directory: ./react/graphql-js
        run: yarn

      - name: Format JavaScript Code
        working-directory: ./react/graphql-js
        run: yarn format:write

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Format Terraform Code
        working-directory: ./react/graphql-js/infra
        run: terraform fmt

      - name: Commit and Push Formatting Changes
        run: |
          git config --global --add safe.directory $(realpath .)
          git config user.email "andrew@jarombek.com"
          git config user.name "Andrew Jarombek"
          git add .
          
          if [[ -n $(git status -s) ]]; then
            git commit -m "Format JS Code with Prettier"
            git push
            echo "Changes committed and pushed to the remote repository."
          else
            echo "No local changes to commit and push."
          fi
        shell: bash
