name: React Webpack Seed Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18.16.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Yarn
        working-directory: ./react/webpack-seed
        run: yarn

      - name: Test React Code
        working-directory: ./react/webpack-seed
        run: yarn test
