name: React Webpack Seed Format and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  format_lint:
    runs-on: ubuntu-latest
    container: node:18.16.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Yarn
        working-directory: ./react/webpack-seed
        run: yarn

      - name: Lint JavaScript Code
        working-directory: ./react/webpack-seed
        run: yarn lint

      - name: Format JavaScript Code
        working-directory: ./react/webpack-seed
        run: yarn prettier:check
