name: React Webpack Seed Format and Lint

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  format_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: node:18.16.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Yarn
        working-directory: ./react/webpack-seed
        run: yarn

      - name: Lint JavaScript Code
        working-directory: ./react/webpack-seed
        run: yarn lint

      - name: Format JavaScript Code
        working-directory: ./react/webpack-seed
        run: yarn prettier:check
