name: React GraphQL JS Format Commit

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:

jobs:
  format_commit:
    runs-on: ubuntu-latest
    container: node:18.16.1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Yarn
        working-directory: ./react/graphql-js
        run: yarn

      - name: Format JavaScript Code
        working-directory: ./react/graphql-js
        run: yarn format:write

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Format Terraform Code
        working-directory: ./react/graphql-js/infra
        run: terraform fmt

      - name: Commit and Push Formatting Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Andrew Jarombek
          author_email: andrew@jarombek.com
          message: 'Format JS Code with Prettier'
